[tool.poetry]
name = "pyona"
version = "0.1.0"
description = "A Python API library for Open NARS for Applications (ONA)"
authors = ["Adrian Borucki <ab@synthillect.ai>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.270"
pytest = "^7.3.1"

[build-system]
#requires = ["setuptools", "wheel"]
#build-backend = "setuptools.build_meta"
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
pure_python = false

[tool.hatch.build.targets.wheel.hooks.autorun]
dependencies = ["hatch-autorun"]
code = """
os.environ["NARS_HOME"] = os.path.dirname(os.path.abspath(__file__))
"""

[project]
name = "pyona"
version = "0.1.0"
description = "A Python API library for Open NARS for Applications (ONA)"
authors = ["Adrian Borucki <ab@synthillect.ai>"]
license = "Apache-2.0"
readme = "README.md"
#dependencies = [
#    "requests",
#]
